import { StyleSheet } from 'react-native';

const colors = {
  background: '#FFFFFF',
  surface: '#FAFAFA',
  surfaceMuted: '#F4F4F4',
  border: '#E3E3E3',
  borderStrong: '#C8C8C8',
  text: '#111111',
  textSecondary: '#666666',
  textMuted: '#8A8A8A',
  inverse: '#FFFFFF',
  primary: '#111111',
  success: '#2E7D32',
  successSoft: '#EAF5EC',
  overlay: 'rgba(0, 0, 0, 0.48)',
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    minHeight: 52,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBack: {
    color: colors.text,
    fontSize: 38,
    fontWeight: '300',
    lineHeight: 40,
  },
  headerProgress: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  headerMenu: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '700',
    lineHeight: 30,
  },
  progressTrack: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 24,
    paddingBottom: 12,
  },
  progressSegment: {
    flex: 1,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  progressSegmentActive: {
    backgroundColor: colors.primary,
  },
  progressSegmentCompleted: {
    backgroundColor: colors.success,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 22,
    paddingBottom: 36,
  },
  exerciseHeading: {
    alignItems: 'center',
    marginBottom: 24,
  },
  exerciseTitle: {
    color: colors.text,
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
  },
  exerciseSubtitle: {
    color: colors.textSecondary,
    fontSize: 16,
    marginTop: 6,
    textAlign: 'center',
  },
  card: {
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surface,
  },
  compactCard: {
    paddingVertical: 14,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  compactCardHeader: {
    marginBottom: 8,
  },
  cardTitleGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  cardIcon: {
    color: colors.text,
    fontSize: 20,
    fontWeight: '700',
  },
  cardTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
  },
  editButton: {
    padding: 4,
  },
  editButtonText: {
    color: colors.textSecondary,
    fontSize: 25,
  },
  descriptionBox: {
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.background,
  },
  descriptionText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 22,
  },
  placeholderText: {
    color: colors.textMuted,
    fontStyle: 'italic',
  },
  cardHint: {
    color: colors.textMuted,
    fontSize: 12,
    marginTop: 10,
  },
  prIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    color: colors.success,
    backgroundColor: colors.successSoft,
    fontSize: 20,
    fontWeight: '800',
    lineHeight: 30,
    textAlign: 'center',
  },
  dateBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    color: colors.textSecondary,
    backgroundColor: colors.surfaceMuted,
    fontSize: 12,
  },
  prValue: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '700',
    lineHeight: 26,
  },
  prValueCompact: {
    fontSize: 15,
    lineHeight: 21,
  },
  prType: {
    color: colors.textSecondary,
    fontSize: 13,
    marginTop: 5,
  },
  emptyCardText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  sectionIcon: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  infoIcon: {
    color: colors.textMuted,
    fontSize: 19,
  },
  setTypeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  setTypeCard: {
    width: '48%',
    minHeight: 82,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.background,
  },
  selectedCard: {
    borderColor: colors.primary,
    backgroundColor: colors.surfaceMuted,
  },
  setTypeIcon: {
    fontSize: 21,
    marginBottom: 6,
  },
  setTypeLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  selectedText: {
    color: colors.text,
    fontWeight: '800',
  },
  infoBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  infoBannerIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    color: colors.inverse,
    backgroundColor: colors.primary,
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 28,
    textAlign: 'center',
  },
  infoBannerText: {
    flex: 1,
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 19,
  },
  primaryButton: {
    width: '100%',
    minHeight: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: colors.primary,
  },
  disabledButton: {
    opacity: 0.35,
  },
  primaryButtonText: {
    color: colors.inverse,
    fontSize: 17,
    fontWeight: '800',
  },
  primaryButtonArrow: {
    position: 'absolute',
    right: 20,
    color: colors.inverse,
    fontSize: 25,
    fontWeight: '400',
  },
  linkButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  linkButtonText: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  badgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginBottom: 16,
  },
  badge: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.background,
  },
  badgeText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  selectedBadge: {
    borderColor: colors.borderStrong,
    backgroundColor: colors.surfaceMuted,
  },
  selectedBadgeText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  formCard: {
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    backgroundColor: colors.surface,
  },
  stepperSection: {
    gap: 14,
  },
  inputLabel: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  stepperRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  stepperButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.borderStrong,
    borderRadius: 11,
    backgroundColor: colors.background,
  },
  stepperButtonText: {
    color: colors.text,
    fontSize: 29,
    fontWeight: '300',
    lineHeight: 31,
  },
  valueContainer: {
    minWidth: 100,
    alignItems: 'center',
  },
  valueInput: {
    minWidth: 100,
    padding: 0,
    color: colors.text,
    fontSize: 32,
    fontWeight: '500',
    lineHeight: 38,
    textAlign: 'center',
  },
  valueUnit: {
    color: colors.textMuted,
    fontSize: 14,
  },
  formDivider: {
    height: 1,
    marginVertical: 18,
    backgroundColor: colors.border,
  },
  failureGrid: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 12,
  },
  failureButton: {
    flex: 1,
    minHeight: 60,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 9,
    backgroundColor: colors.background,
  },
  failureText: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: colors.overlay,
  },
  sheetBackdrop: {
    flex: 1,
  },
  sheet: {
    maxHeight: '88%',
    paddingHorizontal: 18,
    paddingTop: 10,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    backgroundColor: colors.background,
  },
  sheetHandle: {
    width: 42,
    height: 5,
    alignSelf: 'center',
    marginBottom: 22,
    borderRadius: 3,
    backgroundColor: colors.borderStrong,
  },
  sheetTitle: {
    color: colors.text,
    fontSize: 23,
    fontWeight: '800',
    textAlign: 'center',
  },
  sheetSubtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 7,
    marginBottom: 18,
    textAlign: 'center',
  },
  sheetOption: {
    minHeight: 82,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 13,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surface,
  },
  finishOption: {
    borderColor: colors.success,
    backgroundColor: colors.successSoft,
  },
  sheetOptionIcon: {
    width: 32,
    color: colors.text,
    fontSize: 25,
    fontWeight: '700',
    textAlign: 'center',
  },
  sheetOptionContent: {
    flex: 1,
  },
  sheetOptionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sheetOptionTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '800',
  },
  suggestedBadge: {
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: colors.surfaceMuted,
  },
  suggestedBadgeText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '700',
  },
  sheetOptionDescription: {
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  sheetActionArrow: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '500',
  },
  cancelButton: {
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  cancelButtonText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  emptyStateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  emptyStateTitle: {
    color: colors.text,
    fontSize: 23,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyStateDescription: {
    color: colors.textSecondary,
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 22,
    textAlign: 'center',
  },
  timerOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1000,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.96)',
  },
  timerTitle: {
    color: colors.inverse,
    fontSize: 22,
    fontWeight: '800',
    marginBottom: 36,
  },
  timerSeconds: {
    color: colors.inverse,
    fontSize: 112,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  timerLabel: {
    color: '#A0A0A0',
    fontSize: 17,
    marginBottom: 52,
  },
  skipTimerButton: {
    paddingHorizontal: 36,
    paddingVertical: 14,
    borderWidth: 2,
    borderColor: colors.inverse,
    borderRadius: 28,
  },
  skipTimerText: {
    color: colors.inverse,
    fontSize: 16,
    fontWeight: '700',
  },
});
