import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  exerciseNavWrapper: {
    backgroundColor: '#f5f5f5',
    borderBottomWidth: 1,
    borderColor: '#e5e5e5',
  },
  exerciseNavContainer: {
    paddingVertical: 12,
  },
  exerciseNavContent: {
    paddingHorizontal: 16,
    gap: 8,
  },
  exerciseNavTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  exerciseNavTabActive: {
    backgroundColor: '#000',
    borderColor: '#000',
  },
  exerciseNavTabCompleted: {
    borderColor: '#34C759',
    backgroundColor: '#E8F5E9',
  },
  exerciseNavTabSkipped: {
    borderColor: '#FFBB00',
    backgroundColor: '#FFFDE7',
  },
  exerciseNavTabText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '600',
  },
  exerciseNavTabTextActive: {
    color: '#fff',
  },
  exerciseNavTabTextCompleted: {
    color: '#1B5E20',
  },
  exerciseNavTabTextSkipped: {
    color: '#F57F17',
  },
  scrollContent: {
    flexGrow: 1,
    padding: 24,
    paddingBottom: 100, // Extra padding for FAB space
  },
  title: {
    width: '100%',
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
    paddingVertical: 12,
    backgroundColor: 'black',
    color: 'white',
  },
  exerciseInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 16,
    gap: 16,
  },
  exerciseInfoTextContainer: {
    flex: 1,
  },
  muscleBadge: {
    width: 50,
    height: 50,
    backgroundColor: '#000',
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
  },
  muscleText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  exerciseName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#000',
  },
  performanceContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 16,
  },
  performanceItem: {
    flex: 1,
    backgroundColor: '#000',
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
  },
  performanceLabel: {
    fontSize: 9,
    color: '#aaa',
    textTransform: 'uppercase',
    fontWeight: 'bold',
    marginBottom: 2,
  },
  performanceValue: {
    fontSize: 13,
    color: '#fff',
    fontWeight: 'bold',
  },
  exerciseDescriptionContainer: {
    backgroundColor: '#f5f5f5',
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#000',
    marginBottom: 16,
  },
  exerciseDescriptionText: {
    fontSize: 14,
    color: '#333',
    fontStyle: 'italic',
    lineHeight: 20,
  },
  addDescriptionText: {
    fontSize: 14,
    color: '#666',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#eee',
    marginVertical: 12,
  },
  loggedSetsContainer: {
    gap: 8,
  },
  sectionSubtitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000',
    marginBottom: 4,
  },
  loggedSetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f9f9f9',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    gap: 12,
  },
  loggedSetIndex: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#666',
    width: 24,
  },
  loggedSetDetails: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  loggedSetTypeText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
  },
  loggedSetValueText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  loggedSetNotes: {
    fontSize: 12,
    color: '#888',
    fontStyle: 'italic',
  },
  setFormContent: {
    gap: 16,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  inputContainer: {
    gap: 6,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 15,
    color: '#000',
    backgroundColor: '#f9f9f9',
  },
  setTypeSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  setTypeChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  setTypeChipSelected: {
    backgroundColor: 'black',
    borderColor: 'black',
  },
  setTypeChipText: {
    fontSize: 13,
    color: '#555',
    fontWeight: '500',
  },
  setTypeChipTextSelected: {
    color: 'white',
  },
  failureTypeSelector: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  failureTypeChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
  },
  failureTypeChipSelected: {
    backgroundColor: 'black',
    borderColor: 'black',
  },
  failureTypeChipText: {
    fontSize: 13,
    color: '#555',
    fontWeight: '500',
  },
  failureTypeChipTextSelected: {
    color: 'white',
  },
  saveButton: {
    backgroundColor: 'black',
    padding: 14,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 8,
  },
  saveButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
    textTransform: 'uppercase',
  },
  waitingText: {
    fontSize: 14,
    color: '#888',
    fontStyle: 'italic',
    textAlign: 'center',
    marginVertical: 8,
  },
  navigationButtonsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 24,
    gap: 12,
  },
  navBtn: {
    flex: 1,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  navBtnDisabled: {
    opacity: 0.3,
  },
  navBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  skipBtn: {
    flex: 1.2,
    paddingVertical: 12,
    backgroundColor: '#FFF9C4', // Soft warning yellow
    borderWidth: 1,
    borderColor: '#FBC02D',
    borderRadius: 8,
    alignItems: 'center',
  },
  skipBtnText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#F57F17',
  },
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    zIndex: 10,
  },
  fabIcon: {
    fontSize: 24,
    color: 'white',
    fontWeight: 'bold',
  },
  timerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  timerTitle: {
    color: 'white',
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 40,
    textTransform: 'uppercase',
  },
  timerSeconds: {
    color: 'white',
    fontSize: 120,
    fontWeight: '800',
    fontVariant: ['tabular-nums'],
  },
  timerLabel: {
    color: '#8E8E93',
    fontSize: 18,
    marginTop: -10,
    marginBottom: 60,
  },
  skipTimerButton: {
    paddingHorizontal: 40,
    paddingVertical: 16,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: 'white',
  },
  skipTimerText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
});