import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: '#8E8E93',
    fontSize: 15,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 16,
    paddingBottom: 28,
  },
  emptyScrollContent: {
    justifyContent: 'center',
  },
  disclaimer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#D8D8DC',
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
  },
  disclaimerIcon: {
    width: 22,
    height: 22,
    color: '#FFFFFF',
    backgroundColor: '#1C1C1E',
    borderRadius: 11,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 22,
    textAlign: 'center',
  },
  disclaimerText: {
    flex: 1,
    color: '#636366',
    fontSize: 13,
    lineHeight: 18,
  },
  routineCard: {
    minHeight: 96,
    justifyContent: 'center',
    padding: 16,
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  routineCardTitle: {
    flex: 1,
    color: '#1C1C1E',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  routineCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  templateBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#E8E8EB',
  },
  templateBadgeText: {
    color: '#636366',
    fontSize: 11,
    fontWeight: '700',
  },
  routineCardDescription: {
    color: '#8E8E93',
    fontSize: 14,
  },
  addRoutineButton: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: '#8E8E93',
    borderStyle: 'dashed',
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  addRoutineIcon: {
    color: '#1C1C1E',
    fontSize: 22,
    fontWeight: '500',
  },
  addRoutineText: {
    color: '#1C1C1E',
    fontSize: 15,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 48,
  },
  emptyIconContainer: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    borderRadius: 36,
    backgroundColor: '#E8E8EB',
  },
  emptyIcon: {
    color: '#1C1C1E',
    fontSize: 36,
    fontWeight: '300',
  },
  emptyTitle: {
    color: '#1C1C1E',
    fontSize: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    maxWidth: 320,
    color: '#8E8E93',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 24,
    textAlign: 'center',
  },
});
