import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F7',
  },
  innerContainer: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  title: {
    color: '#1C1C1E',
    fontSize: 28,
    fontWeight: '700',
  },
  hint: {
    color: '#8E8E93',
    fontSize: 14,
    fontWeight: '500',
    marginTop: 5,
    marginBottom: 16,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 28,
  },
  emptyScrollContent: {
    justifyContent: 'center',
  },
  workoutCard: {
    minHeight: 96,
    justifyContent: 'center',
    padding: 16,
    marginBottom: 12,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
  },
  workoutCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 4,
  },
  workoutCardTitle: {
    flex: 1,
    color: '#1C1C1E',
    fontSize: 18,
    fontWeight: '600',
  },
  editWorkoutButton: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 18,
    backgroundColor: '#F2F2F7',
  },
  editWorkoutIcon: {
    fontSize: 17,
  },
  workoutCardDescription: {
    color: '#8E8E93',
    fontSize: 14,
    marginBottom: 2,
  },
  addWorkoutButton: {
    minHeight: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    borderColor: '#8E8E93',
    borderStyle: 'dashed',
    borderRadius: 12,
    backgroundColor: 'transparent',
  },
  addWorkoutIcon: {
    color: '#1C1C1E',
    fontSize: 22,
    fontWeight: '500',
  },
  addWorkoutText: {
    color: '#1C1C1E',
    fontSize: 15,
    fontWeight: '700',
  },
  emptyState: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingBottom: 48,
  },
  emptyIconContainer: {
    width: 72,
    height: 72,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
    borderRadius: 36,
    backgroundColor: '#E8E8EB',
  },
  emptyIcon: {
    color: '#1C1C1E',
    fontSize: 36,
    fontWeight: '300',
  },
  emptyTitle: {
    color: '#1C1C1E',
    fontSize: 21,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    maxWidth: 320,
    color: '#8E8E93',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 8,
    marginBottom: 24,
    textAlign: 'center',
  },
});
